export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const SHOW_ERROR_FORM = "SHOW_ERROR_FORM";
export const SELECT_PROJECT = "SELECT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const TASK_PROJECTS = "TASK_PROJECTS";
export const ADD_TASK = "ADD_TASK";
export const SHOW_ERROR_TASKFORM = "SHOW_ERROR_TASKFORM";
export const DELETE_TASK = "DELETE_TASK";
export const TASK_COMPLETE = "TASK_COMPLETE";
export const CURRENT_TASK = "CURRENT_TASK";
export const EDIT_TASK = "EDIT_TASK";
